### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [slyrus/clem#5]
Building with SBCL 2.1.6 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 5eb055bb3f45840b24fd44825b975aa36bd6d97c

*clem-benchmark* fails to build because of a failure in  _clem_.

*clem-test* fails to build because of a failure in  _clem_.

*clem* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Lock on package SB-C violated when interning %ARRAY-DATA-VECTOR while in package CLEM.
;   See also:
;     The SBCL Manual, Node "Package Locks"(in form starting at line: 9, column: 0, position: 159)
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A18103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "clem" "src" "typed-ops" "defmatrix-mult">

```

[Full log here](http://report.quicklisp.org/2021-07-02/failure-report/clem.html)

**Comment by slyrus** [comment]
Thanks for the report. Fixed.
